apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: addon-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addon-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: addon-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - addon-operator
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: ADDON_OPERATOR_POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ADDON_OPERATOR_HA
          value: "true"
        - name: ADDON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ADDON_OPERATOR_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: registry.mycompany.com/addon-operator:ha
        imagePullPolicy: IfNotPresent
        name: addon-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9650
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: addon-operator-acc
      serviceAccountName: addon-operator-acc
      terminationGracePeriodSeconds: 30
