#!/bin/bash

# dependency: gamma
# dependency: delta

# enabled if gamma and delta are enabled

cat ${VALUES_PATH:-/dev/null} | jq '.global.enabledModules | any(in({"gamma":1,"delta":1}))' > $MODULE_ENABLED_RESULT
