apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: default
  labels:
    app: database
spec:
  containers:
  - name: database
    image: postgres:13-alpine
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: db-config
