#!/bin/bash -e

if [[ "$1" == "--config" ]]; then
  cat <<EOF
configVersion: v1
afterDeleteHelm: 20
EOF
else
    cat << 'EOF' > "$VALUES_JSON_PATCH_PATH"
[
    { "op": "add", "path": "/module/afterDeleteHelm", "value": "value-from-after-delete-helm-20" }
]
EOF
fi
