#!/bin/bash -e

if [[ "$1" == "--config" ]]; then
  cat <<EOF
configVersion: v1
beforeHelm: 2
EOF
else
    cat << 'EOF' > "$VALUES_JSON_PATCH_PATH"
[
    { "op": "add", "path": "/module/afterHelm", "value": "value-from-before-helm-2" }
]
EOF
fi
