FROM flant/addon-operator:latest
LABEL app="addon-operator" example="202-module-symlinks"

# Add modules.
ADD global-hooks /global-hooks
ADD module_storage /module_storage
ADD module_dir_1 /module_dir_1
ADD module_dir_2 /module_dir_2
