---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-operator
  labels:
    app: addon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addon-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: addon-operator
    spec:
      containers:
      - name: addon-operator
        image: localhost:5000/addon-operator:example-202
        imagePullPolicy: Always
        env:
        - name: MODULES_DIR
          value: "/module_dir_1:/module_dir_2"
        - name: ADDON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9650
      serviceAccountName: addon-operator-202

