#!/bin/bash -e

if [[ "$1" == "--config" ]]; then
  cat <<EOF
configVersion: v1
beforeAll: 1
EOF
else
  cat <<'EOF' > "$VALUES_JSON_PATCH_PATH"
[
    { "op": "add", "path": "/global/a", "value": 9 },
    { "op": "add", "path": "/global/c", "value": "10" }
]
EOF
fi
