---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-operator
  labels:
    app: addon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addon-operator
  template:
    metadata:
      labels:
        app: addon-operator
    spec:
      containers:
      - name: addon-operator
        image: registry.mycompany.com/addon-operator:sysctl-tuner
        imagePullPolicy: Always
        env:
        - name: ADDON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9650
      serviceAccountName: addon-operator-acc

