apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: alpine:3.16
        imagePullPolicy: IfNotPresent
        command: ['/bin/ash', '-c', 'trap "echo Catch SIGINT, quit now" TERM INT; sleep 100000 & wait']
