apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: alpine:3.16
        imagePullPolicy: IfNotPresent
        command: ['/bin/ash', '-c', 'trap "echo Catch SIGINT, quit now" TERM INT; sleep 100000 & wait']
