# every push to a branch: build a binary
name: Build
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_binary:
    name: Build addon-operator binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
        id: go

      - name: Check out addon-operator code
        uses: actions/checkout@v5

      - name: Restore Go modules
        id: go-modules-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Download Go modules
        if: steps.go-modules-cache.outputs.cache-hit != 'true'
        run: |
          go mod download
          echo -n "Go modules unpacked size is: " && du -sh $HOME/go/pkg/mod

      - name: Build binary
        run: |
          export GOOS=linux

          go build ./cmd/addon-operator