# every push to a branch:
# - check grammar
# - go fmt
name: Code checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_style:
    name: Go code style
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out addon-operator code
        uses: actions/checkout@v3

      - name: Ensure code is gofmted
        run: |
          gofmt -d $(find . -type f -iname '*.go')

  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Check out addon-operator code
        uses: actions/checkout@v3

      - name: codespell
        run: |
          pip install codespell==v1.17.1
          codespell --skip=".git,go.mod,go.sum,*.log,*.gif,*.png" -L witht,eventtypes,uint,uptodate,afterall
