# every push to a branch:
# - run linter
name: Lint
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run_linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Check out addon-operator code
        uses: actions/checkout@v3

      - name: Restore Go modules
        id: go-modules-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Download Go modules
        if: steps.go-modules-cache.outputs.cache-hit != 'true'
        run: |
          go mod download
          echo -n "Go modules unpacked size is: " && du -sh $HOME/go/pkg/mod

      - name: Download prebuilt libjq static libraries
        run: |
          curl -sSfL https://github.com/flant/libjq-go/releases/download/jq-b6be13d5-0/libjq-glibc-amd64.tgz | tar zxf -

      - name: Run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b . v1.50.1
          ./golangci-lint run --sort-results --timeout 5m 
