# Build flant/addon-operator-dev images from pull requests
# and push to hub.docker.com when PR is labeled
# with label "publish/image/dev"
name: Publish dev images
on:
  pull_request:
    types: [labeled]
env:
  QEMU_PLATFORMS: arm64,arm
  BUILDX_PLATFORMS: "linux/amd64"
  IMAGE_REPO: flant/addon-operator-dev

jobs:
  check_label:
    name: Check and remove label
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/github-script@v5
        id: check
        with:
          script: |
            const labelName = context.payload.label.name;
            if (labelName !== 'publish/image/dev') {
              return console.log(`Ignore label '${labelName}': do not run 'publish dev image'.`);
            }
            console.log(`Detect label '${labelName}': remove it and run 'publish dev image'.`);
            core.setOutput('should_run', 'true');
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: labelName,
              });
            } catch (e) {
              console.log(`Error occurred while remove label. Possibly label is already removed. Ignore '${typeof e}' error.`);
            }

  build_dev_image:
    name: Build and publish
    runs-on: ubuntu-latest
    needs:
      - check_label
    if: needs.check_label.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v2.4.0

      # Copy-paste from publish-release.yaml till the end
      - name: Prepare environment
        run: |
          : Image name and version for dev image
          # dev-feat_branch-371e2d3b-2020.02.06_18:37:42
          APP_VERSION=dev-${GITHUB_REF#refs/heads/}-${GITHUB_SHA::8}-$(date +'%Y.%m.%d_%H:%M:%S')
          FINAL_IMAGE_NAME="${IMAGE_REPO}:pr${{ github.event.pull_request.number }}"

          echo "APP_VERSION=${APP_VERSION}" >> ${GITHUB_ENV}
          echo "FINAL_IMAGE_NAME=${FINAL_IMAGE_NAME}" >> ${GITHUB_ENV}

          echo "========================================="
          echo "APP_VERSION        = $APP_VERSION"
          echo "FINAL_IMAGE_NAME   = $FINAL_IMAGE_NAME"
          echo "========================================="

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: "${{ env.QEMU_PLATFORMS }}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push multi-arch image
        run: |
          echo "Build $FINAL_IMAGE_NAME with version '$APP_VERSION'"
          docker buildx build --push \
              --platform $BUILDX_PLATFORMS \
              --build-arg appVersion=$APP_VERSION \
              --tag $FINAL_IMAGE_NAME .

      - name: Inspect binaries
        run: |
          while read digest platform ; do
            echo "Inspect image for platform=${platform}"
            docker run --rm --platform ${platform} --entrypoint sh $FINAL_IMAGE_NAME@${digest} -c \
              'apk add file > /dev/null; file /bin/kubectl; file /bin/busybox; file /addon-operator; file /bin/helm'
          done <<< $(docker buildx imagetools inspect $FINAL_IMAGE_NAME --raw | jq '.manifests//[{"digest":.config.digest, "platform":{"os":"linux","architecture":"amd64"}}] | .[] | .digest + " " + .platform.os +"/"+.platform.architecture' -r)
